/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { BannerCampaignService } from "../bannerCampaign.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BannerCampaignCreateInput } from "./BannerCampaignCreateInput";
import { BannerCampaignWhereInput } from "./BannerCampaignWhereInput";
import { BannerCampaignWhereUniqueInput } from "./BannerCampaignWhereUniqueInput";
import { BannerCampaignFindManyArgs } from "./BannerCampaignFindManyArgs";
import { BannerCampaignUpdateInput } from "./BannerCampaignUpdateInput";
import { BannerCampaign } from "./BannerCampaign";
import { BannerFindManyArgs } from "../../banner/base/BannerFindManyArgs";
import { Banner } from "../../banner/base/Banner";
import { BannerWhereUniqueInput } from "../../banner/base/BannerWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class BannerCampaignControllerBase {
  constructor(
    protected readonly service: BannerCampaignService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "BannerCampaign",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: BannerCampaign })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: BannerCampaignCreateInput
  ): Promise<BannerCampaign> {
    return await this.service.create({
      data: {
        ...data,

        client: {
          connect: data.client,
        },
      },
      select: {
        client: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "BannerCampaign",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [BannerCampaign] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(BannerCampaignFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<BannerCampaign[]> {
    const args = plainToClass(BannerCampaignFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        client: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "BannerCampaign",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: BannerCampaign })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: BannerCampaignWhereUniqueInput
  ): Promise<BannerCampaign | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        client: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "BannerCampaign",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: BannerCampaign })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: BannerCampaignWhereUniqueInput,
    @common.Body() data: BannerCampaignUpdateInput
  ): Promise<BannerCampaign | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          client: {
            connect: data.client,
          },
        },
        select: {
          client: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "BannerCampaign",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: BannerCampaign })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: BannerCampaignWhereUniqueInput
  ): Promise<BannerCampaign | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          client: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Banner",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/banners")
  @ApiNestedQuery(BannerFindManyArgs)
  async findManyBanners(
    @common.Req() request: Request,
    @common.Param() params: BannerCampaignWhereUniqueInput
  ): Promise<Banner[]> {
    const query = plainToClass(BannerFindManyArgs, request.query);
    const results = await this.service.findBanners(params.id, {
      ...query,
      select: {
        asset: {
          select: {
            id: true,
          },
        },

        campaigns: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        size: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "BannerCampaign",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/banners")
  async connectBanners(
    @common.Param() params: BannerCampaignWhereUniqueInput,
    @common.Body() body: BannerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      banners: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "BannerCampaign",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/banners")
  async updateBanners(
    @common.Param() params: BannerCampaignWhereUniqueInput,
    @common.Body() body: BannerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      banners: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "BannerCampaign",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/banners")
  async disconnectBanners(
    @common.Param() params: BannerCampaignWhereUniqueInput,
    @common.Body() body: BannerWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      banners: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
