/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { BannerService } from "../banner.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { BannerCreateInput } from "./BannerCreateInput";
import { BannerWhereInput } from "./BannerWhereInput";
import { BannerWhereUniqueInput } from "./BannerWhereUniqueInput";
import { BannerFindManyArgs } from "./BannerFindManyArgs";
import { BannerUpdateInput } from "./BannerUpdateInput";
import { Banner } from "./Banner";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class BannerControllerBase {
  constructor(
    protected readonly service: BannerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Banner",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Banner })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(@common.Body() data: BannerCreateInput): Promise<Banner> {
    return await this.service.create({
      data: {
        ...data,

        asset: {
          connect: data.asset,
        },

        campaigns: data.campaigns
          ? {
              connect: data.campaigns,
            }
          : undefined,
      },
      select: {
        asset: {
          select: {
            id: true,
          },
        },

        campaigns: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        size: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Banner",
    action: "read",
    possession: "any",
  })
  @common.Get()
  @swagger.ApiOkResponse({ type: [Banner] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(BannerFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<Banner[]> {
    const args = plainToClass(BannerFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        asset: {
          select: {
            id: true,
          },
        },

        campaigns: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        size: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Banner",
    action: "read",
    possession: "own",
  })
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Banner })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: BannerWhereUniqueInput
  ): Promise<Banner | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        asset: {
          select: {
            id: true,
          },
        },

        campaigns: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        size: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "Banner",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Banner })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: BannerWhereUniqueInput,
    @common.Body() data: BannerUpdateInput
  ): Promise<Banner | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          asset: {
            connect: data.asset,
          },

          campaigns: data.campaigns
            ? {
                connect: data.campaigns,
              }
            : undefined,
        },
        select: {
          asset: {
            select: {
              id: true,
            },
          },

          campaigns: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          size: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "Banner",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Banner })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: BannerWhereUniqueInput
  ): Promise<Banner | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          asset: {
            select: {
              id: true,
            },
          },

          campaigns: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          size: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
